[build-system]
requires = ["setuptools", "wheel", "scikit-build", "cmake", "ninja"]

[tool.pytest.ini_options]
markers = [
  "needs_polarizationsolver: marks tests that need the polarizationsolver Python library (deselect with '-m \"not needs_polarizationsolver\"')",
]
