libcppe::InducedMoments
std::vector<Potential> libcppe::InducedMoments::m_potentials
vector with all site potentials
Referenced by compute, InducedMoments.
std::vector<Potential> libcppe::InducedMoments::m_polsites
vector with all potentials of polarizable sites
Referenced by compute, InducedMoments.
size_t libcppe::InducedMoments::m_n_polsites
number of polarizable sites
Referenced by compute, InducedMoments.
PeOptions libcppe::InducedMoments::m_options
Referenced by compute.
libcppe::InducedMoments::InducedMoments(std::vector< Potential > potentials, PeOptions options)
References m_polsites, libcppe::get_polarizable_sites, m_potentials, m_n_polsites.
libcppe::InducedMoments::~InducedMoments()
void libcppe::InducedMoments::compute(const Eigen::VectorXd &total_fields, Eigen::VectorXd &induced_moments, bool make_guess, std::ostream &output_stream=std::cout)
References libcppe::Tk_coefficients, m_potentials, libcppe::smat_vec, m_options, libcppe::PeOptions::diis_maxiter, libcppe::PeOptions::do_diis, libcppe::PeOptions::induced_thresh, libcppe::PeOptions::diis_start_norm, m_n_polsites, m_polsites, libcppe::Potential::excludes_site, libcppe::Potential::index, libcppe::Potential::get_site_position, libcppe::Tk_tensor, libcppe::Potential::get_polarizabilities.
Referenced by libcppe::CppeState::update_induced_moments, compute, export_fields.
Eigen::VectorXd libcppe::InducedMoments::compute(Eigen::VectorXd &total_fields, bool make_guess)
overloads the compute method for induced moments and returns a copy of the induced moments vector
References compute.