libcppe::CppeState
Eigen::MatrixXd libcppe::CppeState::m_es_operator
PE electrostatics operator.
PeEnergy libcppe::CppeState::m_pe_energy
PE Energy Container.
Referenced by CppeState, calculate_static_energies_and_fields, update_induced_moments, print_summary, get_energies, set_energies.
Molecule libcppe::CppeState::m_mol
core region molecule
Referenced by CppeState, calculate_static_energies_and_fields, set_molecule.
std::vector<Potential> libcppe::CppeState::m_potentials
vector with all site potentials
Referenced by set_potentials, calculate_static_energies_and_fields, update_induced_moments, get_potentials.
size_t libcppe::CppeState::m_polarizable_sites
number of polarizable sites
Referenced by set_potentials, update_induced_moments, get_polarizable_site_number.
Eigen::VectorXd libcppe::CppeState::m_nuc_fields
electric fields from nuclei
Referenced by calculate_static_energies_and_fields, update_induced_moments, get_static_fields.
Eigen::VectorXd libcppe::CppeState::m_multipole_fields
electric fields from multipole moments
Referenced by calculate_static_energies_and_fields, update_induced_moments, get_static_fields.
Eigen::VectorXd libcppe::CppeState::m_induced_moments
Vector with induced moments.
Referenced by set_potentials, update_induced_moments, get_induced_moments, get_induced_moments_vec.
PeOptions libcppe::CppeState::m_options
Referenced by CppeState, update_induced_moments, set_options.
std::ostream& libcppe::CppeState::m_output_stream
Output stream for printing.
Referenced by update_induced_moments, print_summary.
bool libcppe::CppeState::m_make_guess
Referenced by update_induced_moments.
libcppe::CppeState::CppeState()
libcppe::CppeState::CppeState(PeOptions options, Molecule mol, std::ostream &=std::cout)
References m_pe_energy, m_options, libcppe::PeOptions::potfile, libcppe::PotfileReader::read, m_mol, libcppe::PotManipulator::manipulate, set_potentials.
libcppe::CppeState::~CppeState()
void libcppe::CppeState::set_options(PeOptions options)
References m_options.
void libcppe::CppeState::set_molecule(Molecule mol)
References m_mol.
void libcppe::CppeState::set_potentials(std::vector< Potential > potentials)
References m_potentials, m_polarizable_sites, m_induced_moments.
Referenced by CppeState, export_state.
std::vector<Potential> libcppe::CppeState::get_potentials()
References m_potentials.
Referenced by export_state.
PeEnergy& libcppe::CppeState::get_energies()
References m_pe_energy.
Referenced by export_state.
void libcppe::CppeState::set_energies(PeEnergy energy)
References m_pe_energy.
Referenced by export_state.
void libcppe::CppeState::calculate_static_energies_and_fields()
References m_mol, m_potentials, libcppe::MultipoleExpansion::calculate_interaction_energy, m_pe_energy, libcppe::PeEnergy::set, m_nuc_fields, libcppe::NuclearFields::compute, m_multipole_fields, libcppe::MultipoleFields::compute.
Referenced by export_state.
std::vector<double> libcppe::CppeState::get_induced_moments() const
References m_induced_moments.
Referenced by export_state.
Eigen::VectorXd libcppe::CppeState::get_induced_moments_vec() const
References m_induced_moments.
void libcppe::CppeState::update_induced_moments(Eigen::VectorXd elec_fields, bool elec_only=false)
References m_polarizable_sites, m_nuc_fields, m_multipole_fields, m_potentials, m_options, libcppe::InducedMoments::compute, m_induced_moments, m_make_guess, m_output_stream, m_pe_energy, libcppe::PeEnergy::set.
Referenced by export_state.
size_t libcppe::CppeState::get_polarizable_site_number()
References m_polarizable_sites.
Referenced by export_state.
std::vector<double> libcppe::CppeState::get_static_fields()
References m_nuc_fields, m_multipole_fields.
Referenced by export_state.
void libcppe::CppeState::print_summary()
References m_output_stream, m_pe_energy, libcppe::PeEnergy::get, libcppe::PeEnergy::get_total_energy.
Referenced by export_state.