libcppe::Multipole
std::vector<double> libcppe::Multipole::m_values
Referenced by add_value, remove_trace, get_values, get_values_vec.
unsigned libcppe::Multipole::m_k
Referenced by remove_trace, export_multipole.
libcppe::Multipole::Multipole(unsigned k)
libcppe::Multipole::~Multipole()
void libcppe::Multipole::add_value(double val)
References m_values.
Referenced by export_multipole, libcppe::PotfileReader::read.
void libcppe::Multipole::remove_trace()
References m_k, m_values.
Referenced by export_multipole.
std::vector<double>& libcppe::Multipole::get_values()
References m_values.
Eigen::VectorXd libcppe::Multipole::get_values_vec()
References m_values.
Referenced by export_multipole.