libcppe::Polarizability
std::vector<double> libcppe::Polarizability::m_values
Referenced by add_value, get_values_vec, get_values.
libcppe::Polarizability::Polarizability()
libcppe::Polarizability::~Polarizability()
void libcppe::Polarizability::add_value(double val)
References m_values.
Referenced by export_multipole, libcppe::PotfileReader::read.
Eigen::VectorXd libcppe::Polarizability::get_values_vec()
References m_values.
Referenced by export_multipole.
std::vector<double>& libcppe::Polarizability::get_values()
References m_values.