libcppe::Potential
std::vector<Multipole> libcppe::Potential::m_multipoles
Referenced by add_multipole, get_multipoles.
std::vector<Polarizability> libcppe::Potential::m_polarizabilities
Referenced by add_polarizability, get_polarizabilities, is_polarizable.
std::vector<int> libcppe::Potential::m_exclusions
Referenced by add_exclusion, excludes_site, get_exclusions.
double libcppe::Potential::m_x
Referenced by get_site_position, export_multipole.
double libcppe::Potential::m_y
Referenced by get_site_position, export_multipole.
double libcppe::Potential::m_z
Referenced by get_site_position, export_multipole.
int libcppe::Potential::index
Referenced by libcppe::MultipoleFields::compute, libcppe::InducedMoments::compute, export_multipole, libcppe::PotManipulator::manipulate.
libcppe::Potential::Potential(double x, double y, double z, int idx)
libcppe::Potential::~Potential()
void libcppe::Potential::add_multipole(Multipole mul)
References m_multipoles.
void libcppe::Potential::add_polarizability(Polarizability pol)
References m_polarizabilities.
void libcppe::Potential::add_exclusion(int excl)
References m_exclusions.
bool libcppe::Potential::excludes_site(int other_site)
References m_exclusions.
Referenced by libcppe::MultipoleFields::compute, libcppe::InducedMoments::compute.
std::vector<int>& libcppe::Potential::get_exclusions()
References m_exclusions.
std::vector<Multipole>& libcppe::Potential::get_multipoles()
References m_multipoles.
Referenced by libcppe::MultipoleFields::compute, libcppe::MultipoleExpansion::calculate_interaction_energy, export_multipole, libcppe::PotManipulator::manipulate.
std::vector<Polarizability>& libcppe::Potential::get_polarizabilities()
References m_polarizabilities.
Referenced by libcppe::InducedMoments::compute, export_multipole, libcppe::PotManipulator::manipulate.
bool libcppe::Potential::is_polarizable()
References m_polarizabilities.
Referenced by export_multipole.
Eigen::Vector3d libcppe::Potential::get_site_position()
References m_x, m_y, m_z.
Referenced by libcppe::NuclearFields::compute, libcppe::MultipoleFields::compute, libcppe::InducedMoments::compute, libcppe::MultipoleExpansion::calculate_interaction_energy, export_multipole.