libcppe::PotfileReader
std::string libcppe::PotfileReader::m_potfile
Referenced by PotfileReader, read.
libcppe::PotfileReader::PotfileReader(std::string potfile_name)
References m_potfile.
libcppe::PotfileReader::~PotfileReader()
std::vector< Potential > libcppe::PotfileReader::read()
References m_potfile, split, reduce, ang2bohr, libcppe::Site::x, libcppe::Site::y, libcppe::Site::z, libcppe::multipole_components, libcppe::Multipole::add_value, libcppe::Polarizability::add_value.
Referenced by libcppe::CppeState::CppeState, libcppe::CPPE::read_potfile, export_utils.