interface.h
void pe_interface_init_(int *, const double *, const double *)
Referenced by pe_interface_init.
void pe_set_potfile_(const char *, int)
Referenced by pe_set_potfile.
void pe_interface_energy_(const double *, int *, int *)
Referenced by pe_interface_energy.
void pe_interface_pol_energy_(const double *, int *, int *, double *)
Referenced by pe_interface_pol_energy.
void pe_interface_fock_(const double *, int *, int *, const double *, double *)
Referenced by pe_interface_fock.
int gen1int_api_initialized_()
Referenced by gen1int_api_initialized.
void print_shells_()
Referenced by print_shells.
void finalize_all_()
Referenced by finalize_all.
void gen1int_api_initialize_(int *natoms, int *num_shells, const double *coords, const double *charges)
Referenced by gen1int_api_initialize.
void gen1int_create_shell_(int *spher_gto, int *idx_center, const double *coord_center, int *ang_num, int *num_prim, const double *exponents, int *num_contr, const double *contr_coef)
Referenced by gen1int_api_add_shell.
void pe_set_border_options_(int *m_pe_border, double *m_rmin, int *type_flag, int *redist_order, int *nredist)
Referenced by pe_set_border_options.
void pe_interface_init(int n, const double *coords, const double *charges)
References pe_interface_init_.
void pe_set_potfile(const char *c, int n)
References pe_set_potfile_.
void pe_interface_energy(const double *densmat, int ndim, int nnbas)
References pe_interface_energy_.
void pe_interface_fock(const double *densmat, int ndim, int nnbas, const double *fckmat, double *energy)
References pe_interface_fock_.
void pe_interface_pol_energy(const double *densmat, int ndim, int nnbas, double *energy)
References pe_interface_pol_energy_.
int gen1int_api_initialized()
References gen1int_api_initialized_.
void gen1int_api_initialize(int natoms, int num_shells, const double *coords, const double *charges)
References gen1int_api_initialize_.
void gen1int_api_add_shell(int spher_gto, int idx_center, const double *coord_center, int ang_num, int num_prim, const double *exponents, int num_contr, const double *contr_coef)
References gen1int_create_shell_.
void print_shells()
References print_shells_.
void finalize_all()
References finalize_all_.
void pe_set_border_options(int m_pe_border, double m_rmin, int type_flag, int redist_order, int nredist)
References pe_set_border_options_.