libcppe
BorderType
std::map<std::string, std::vector<std::string> > libcppe::ens
Referenced by libcppe::PeEnergy::PeEnergy.
std::vector< Potential > libcppe::get_polarizable_sites(std::vector< Potential > potentials)
Referenced by libcppe::NuclearFields::NuclearFields, libcppe::MultipoleFields::MultipoleFields, libcppe::InducedMoments::InducedMoments.
Eigen::Vector3d libcppe::smat_vec(const Eigen::VectorXd &mat, const Eigen::Vector3d &vec, double alpha)
Referenced by libcppe::InducedMoments::compute, export_math.
Eigen::VectorXd libcppe::Tk_tensor(int k, const Eigen::Vector3d &Rij, std::vector< Eigen::MatrixXi > &Tk_coeffs)
References multipole_components, T.
Referenced by libcppe::NuclearFields::compute, libcppe::InducedMoments::compute, multipole_derivative, libcppe::MultipoleExpansion::calculate_interaction_energy, export_math.
Eigen::VectorXd libcppe::multipole_derivative(int k, int l, const Eigen::Vector3d &Rji, Eigen::VectorXd Mkj, std::vector< Eigen::MatrixXi > &Tk_coeffs)
References factorial, Tk_tensor, xyz2idx, trinom.
Referenced by libcppe::MultipoleFields::compute, export_math.
int libcppe::xyz2idx(int x, int y, int z)
Referenced by multipole_derivative, export_math.
double libcppe::T(const Eigen::Vector3d &Rij, int x, int y, int z, std::vector< Eigen::MatrixXi > &Cijn)
Referenced by Tk_tensor, export_math.
std::vector< Eigen::MatrixXi > libcppe::Tk_coefficients(int max_order)
Referenced by libcppe::NuclearFields::compute, libcppe::MultipoleFields::compute, libcppe::InducedMoments::compute, libcppe::MultipoleExpansion::calculate_interaction_energy, export_math.
double libcppe::factorial(int n)
Referenced by multipole_derivative, make_df, trinom, prefactors, prefactors_nuclei, export_math.
void libcppe::make_df(unsigned k, std::vector< double > &df)
References factorial.
Referenced by export_math.
int libcppe::trinom(int i, int j, int k)
References factorial.
Referenced by multipole_derivative, symmetry_factors, export_math.
std::vector< double > libcppe::symmetry_factors(unsigned k)
References multipole_components, trinom.
Referenced by prefactors, prefactors_nuclei, export_math.
std::vector< double > libcppe::prefactors(unsigned k)
References factorial, symmetry_factors.
Referenced by export_math.
std::vector< double > libcppe::prefactors_nuclei(unsigned k)
References factorial, symmetry_factors.
Referenced by libcppe::MultipoleExpansion::calculate_interaction_energy, export_math.
int libcppe::multipole_components(int k)
Referenced by Tk_tensor, symmetry_factors, export_math, libcppe::PotManipulator::manipulate, libcppe::PotfileReader::read.
bool libcppe::sortbysec(const std::pair< int, double > &a, const std::pair< int, double > &b)
Referenced by libcppe::PotManipulator::manipulate.