libcppe::PeEnergy
std::vector<PeEnergyContribution> libcppe::PeEnergy::m_energies
Referenced by PeEnergy, get, set, get_total_energy.
libcppe::PeEnergy::PeEnergy()
References libcppe::ens, m_energies.
double libcppe::PeEnergy::get(std::string energy_string)
returns energy contribution from given string
References split, m_energies.
Referenced by libcppe::CppeState::print_summary, export_state.
void libcppe::PeEnergy::set(std::string energy_string, double energy)
sets the energy titled energy_string to energy
energy_string name of the energy contribution energy value void
References split, m_energies.
Referenced by libcppe::CppeState::calculate_static_energies_and_fields, libcppe::CppeState::update_induced_moments, export_state.
double libcppe::PeEnergy::get_total_energy()
returns the total PE energy
References m_energies.
Referenced by libcppe::CppeState::print_summary, export_state.