name: CI

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

env:
  BUILD_TYPE: Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}

    continue-on-error: true

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - 3.8
          - 3.9
          - "3.10"
          - "3.11"

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v3

    # this will set the system compiler;
    # This must be done *before* setting up miniconda, see:
    # https://github.com/ilammy/msvc-dev-cmd/issues/34
    - name: Set Windows env
      if: matrix.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        auto-activate-base: false
        activate-environment: cppe-gha
        environment-file: .github/environment.yml
        channel-priority: true
        python-version: ${{ matrix.python-version }}

    - name: Select CMake CLI options
      run: |
        echo "We are running on ${{ matrix.os }}"
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
           echo "CXX=g++" >> $GITHUB_ENV
        elif [ "${{ matrix.os }}" == "macos-latest" ]; then
           echo "CXX=clang++" >> $GITHUB_ENV
        else
           echo "CXX=clang-cl" >> $GITHUB_ENV
        fi

    - name: Configure
      run: |
        cmake -S. \
              -Bbuild \
              -GNinja \
              -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
              -DCMAKE_CXX_COMPILER=${CXX} \
              -DENABLE_PYTHON_INTERFACE=ON

    - name: Build
      run: |
        cmake --build build --config ${{ env.BUILD_TYPE }} -- -v -d stats

    - name: Test
      run: |
        python -m pip install git+https://gitlab.com/robertodr/polarizationsolver.git@master
        PYTHONPATH=$PYTHONPATH:$PWD/lib/python${{ matrix.python-version }}/site-packages pytest --capture=no --log-cli-level=INFO

    # TODO move to separate workflow
    #- name: Build and Test Setuptools
    #  run: |
    #    rm -rf build
    #    python setup.py install
    #    py.test
