on:
  push:
    tags:
    - 'v*'
  workflow_dispatch:

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, macOS-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build CMake (Linux)
        if: contains( matrix.os, 'ubuntu')
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DENABLE_PYTHON_INTERFACE=OFF -DCMAKE_INSTALL_PREFIX=stage/
          cmake --build build --config $BUILD_TYPE
          cmake --build build --config $BUILD_TYPE --target install
          zip cppe_binary stage/*
          ls
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./cppe_binary.zip
          asset_name: cppe-${{ github.ref }}-${{ runner.os }}.zip
          asset_content_type: application/zip
