name: Publish package

on: workflow_dispatch
  # push:
  #   branches: [master]
  # workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install setuptools and wheel
        run: |
          python -m pip install --user setuptools wheel
      - name: Build a source tarball
        run: |
          python setup.py test
          python setup.py sdist
      - name: Publish distribution 📦 to Test PyPI
        # if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          repository_url: https://test.pypi.org/legacy/
          user: __token__
          password: ${{ secrets.testpypi_password }}